let currentArticle = [ [ { saved: false,
  _id: 5acc04c497f927323c5972e7,
  title: 'Trump Vows Quick Decision on Response to Attack in Syria',
  link: 'https://www.nytimes.com/2018/04/09/world/middleeast/trump-syria-attack.html',
  summary: 'President Trump said Syria’s patrons in Russia and Iran may also be responsible for enabling last weekend’s chemical attack. “Everybody’s going to pay a price,” he said.',
  __v: 0 },
{ saved: false,
  _id: 5acc04c497f927323c5972e8,
  title: 'Zuckerberg to Tell Congress Facebook Made ‘Big Mistake’',
  link: 'https://www.nytimes.com/2018/04/09/technology/mark-zuckerberg-facebook.html',
  summary: 'When he appears before Congress this week, Mark Zuckerberg, Facebook’s chief executive, will issue a broad apology for failing to prevent the mishandling of personal data and other abuses.',
  __v: 0 },
{ saved: false,
  _id: 5acc04c497f927323c5972e9,
  title: 'What Congress Will Ask Zuckerberg',
  link: 'https://www.nytimes.com/2018/04/09/us/politics/mark-zuckerberg-congressional-hearings-topics.html',
  summary: 'Appearing for the first time before a congressional committee, the Facebook founder is likely to be asked about privacy, Russian meddling, fake news and more.',
  __v: 0 },
{ saved: false,
  _id: 5acc04c497f927323c5972eb,
  title: 'Europe Is Caught in the Middle as Trump Threatens China',
  link: 'https://www.nytimes.com/2018/04/09/business/europe-trump-trade-china.html',
  summary: 'The United States is Europe’s biggest trading partner, but China is closing in fast. If a trade war breaks out, neutrality may not be an option.',
  __v: 0 },
{ saved: false,
  _id: 5acc04c497f927323c5972ea,
  title: 'Federal Deficit Projected to Top $1 Trillion by 2020',
  link: 'https://www.nytimes.com/2018/04/09/us/politics/federal-deficit-tax-cuts-spending-trump.html',
  summary: 'The new Congressional Budget Office analysis, which includes the cost of the Republican tax cuts, projects the national debt to reach a level economists say could court a crisis.',
  __v: 0 },
{ saved: false,
  _id: 5acc04c497f927323c5972ec,
  title: 'Florida Braces for Turbulent Campaign as Scott Enters Race',
  link: 'https://www.nytimes.com/2018/04/09/us/florida-rick-scott-senate.html',
  summary: 'Gov. Rick Scott has entered the U.S. Senate race, and Florida will once more be a centerpiece state in a tumultuous election year.',
  __v: 0 },
{ saved: false,
  _id: 5acc04c497f927323c5972ed,
  title: 'Year of the Woman in Politics? In Arizona, Yes, for Both Parties',
  link: 'https://www.nytimes.com/2018/04/09/us/politics/arizona-women-candidates-lesko-tipirneni.html',
  summary: 'Women are playing leading roles across the political spectrum in the state, with Democrats hoping to flip the legislature and Republicans fielding strong female candidates at all levels.',
  __v: 0 } ] ];